development:
    adapter: postgresql
    encoding: unicode
    database: cjpoll_development
    pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: cjpoll_test
    pool: 5
production:
    adapter: postgresql
    encoding: unicode
    database: cjpollmaster
    pool: 5
