development:
    adapter: postgresql
    encoding: unicode
    database: cjpoll_development
    pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: cjpoll_test
    pool: 5

production:
    adapter: postgresql
    encoding: utf8
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>
